### ISSUE TITLE
Hub & Spoke private zone dns linking

### ISSUE THREAD

**Issue by MaxMelcher** [dmauser/PrivateLink#1]
Hi Daniel,

awesome work - wow! I learned so much reading this! **THANK YOU!**

I have one quick question - in the picture in this section https://github.com/dmauser/PrivateLink/tree/master/DNS-Integration-Scenarios#5-architecture-design-example you indicate that you need to link the spoke vnet to the hub vnet to resolve the privatelink records that sit in the hub.

If you have a DNS server in the hub (e.g. https://github.com/microsoft/PL-DNS-Proxy) and set the DNS on the spoke vnet to this server, then you do not need to link every spoke to the privatelink zones - right? Or do you see benefits to it?

I am concerned about the 1000 vnet links per dns zone and the operational effort (e.g. a new private link zone will be added) 

Thanks,
Max

**Comment by dmauser** [comment]
Hi Max,
On that scenario Spokes are optional to use or not DNS Server in the HUB. A VM in the Spoke can reach private endpoint just using regular 168.63.129.16 to consume Private DNS zones. However, you are right on the fact is if you create a VNET link if Private Endpoint resides on the Spoke VNET which you can ends up with several VNET links as you pointed out.

Another approach you can to minimize that would be expose Private Endpoints on the HUB instead and set VNET to use DNS in the HUB. In that case you would not need to link the Spoke VNET to Private DNS zone but only HUB where you have your DNS Server. Also, Azure does not double charge a Private Endpoint over a VNET peering (Check FAQ on: https://azure.microsoft.com/en-us/pricing/details/private-link/).

Probably this is a good topic to explore in another article. I will work on it.

I hope this help,
Thanks,
Daniel
