### ISSUE TITLE
Behavior for OnPrem scenario when Azure Custom DNS is AD integrated

### ISSUE THREAD

**Issue by SumeshP** [dmauser/PrivateLink#2]
Hi,
The doc covers lot of scenarios and is helpful. 
However it is not clear for On-premise scenario 4.1, Solution 1,
"Conditional Forwarder to: blob.core.windows.net Pointing to IP: 10.0.0.10 (IP of Azure Custom DNS server)."

My DNS in Azure is AD integrated. What will happen in this case.
I create a conditional forwarder in on prem and point to Azure 10.0.0.10
Now this will get replicated to my DNS in Azure.
On, Azure i have a non-ad zone with conditional forwarder to 168.63.129.16
In effect Azure DC, will have 2 zones both for "blob.core.windows.net" ?? one ad integrated and another non-ad?
Can you review how this scenario will play out?

**Comment by dmauser** [comment]
OnPrem and Azure Domain Controllers share the same forest or different?
I mean, is Azure DCs on the same Forest as OnPrem DCs, which in theory would replicate AD integrated zone to Azure DCs as well?
Let me know.

**Comment by SumeshP** [comment]
They are in same forest, basically additional DCs for the same on prem Domain.

**Comment by dmauser** [comment]
Ok, in that case you need for OnPrem DCs setup AD integrated with customer DNS Application Partition to limit the scope of replication ton OnPrem DCs only. On Azure you can also do the same thing create a different Application Partition or use as non-AD integrated as you mentioned. 
Take a look on another article related to this setup that I posted last week.
https://github.com/dmauser/PrivateLink/tree/master/DNS-Scenario-Using-AD

I hope this help.
