### ISSUE TITLE
"Add-DnsServerDirectoryPartition  -Computername

### ISSUE THREAD

**Issue by colinweiner** [dmauser/PrivateLink#3]
In the "How to deploy the solution" section it states that "This will require commands to be executed at least in one Domain Controller, it does not matter if they are On-premises or in Azure."  

In step 2, "Create DNS Application Partition" when you run "Add-DnsServerDirectoryPartition -Name $AZDNSADPartition", it will add the the DC that you run it on to the partition.  So for example, if you run it on the On-Prem DC, it will add the On-Prem DC to the AzureDNS Directory Partition,  Once this happens, you will need to unregister it by running the "Unregister-DnsServerDirectoryPartition -Name $AZDNSADPartition -ComputerName $OPDC1".

It would be better to run "Add-DnsServerDirectoryPartition -Name $AZDNSADPartition - ComputerName $AZDC1".  Anyways, thanks this is great content.

**Comment by dmauser** [comment]
Sorry for the delay checking this message (not sure how I missed it). It makes sense. Thanks for catching that.

**Comment by dmauser** [comment]
Updated article with recommendation made by @colinweiner
